# Generated by Django 2.1.5 on 2019-02-13 11:07

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rating', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('high_score', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(verbose_name='game_url')),
                ('number_of_purchases', models.PositiveIntegerField(blank=True, default=0)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_developer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('PE', 'pending'), ('CO', 'confirmed')], default='PE', max_length=9)),
                ('reference', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payee', to='backend.Profile')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payer', to='backend.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Profile'),
        ),
    ]
