# Generated by Django 2.1.3 on 2019-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190218_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('CO', 'Combat'), ('EDU', 'Educational'), ('PZ', 'Puzzle'), ('RPG', 'RPG'), ('SPR', 'Sports'), ('STR', 'Strategy')], max_length=20),
        ),
    ]
